spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/Daile
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  session:
    timeout: 86400
daile:
  jwt-key: "rTPmA9Sgk+Q1XwuJbG7E6xFFUhQpdi+al5iyPnRTK/Q="
server:
  servlet:
    session:
      cookie:
        max-age: 172800

