spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Dailelog?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        one-indexed-parameters: true #1부터시작
        default-page-size: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
